import type { Metadata } from "next";
import Navbar from "./navbar";
import Footer from "./footer";
import { Inter } from "next/font/google";
import 'bulma/css/bulma.css';
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Atlantis System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="pt-br">
    
      <body className={inter.className}><Navbar></Navbar>{children}<Footer></Footer></body>
    </html>
    </>

  );
}
